name: Python Linting

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install pylint==2.12.2
        pylint --version
    - name: Lint with pylint
      run: |
        pylint --rcfile=.pylintrc *.py
        pylint --rcfile=.pylintrc **/*.py
        pylint --rcfile=.pylintrc src/**/*.py
        pylint --rcfile=.pylintrc src/*.py